name: edumunch
description: "EduMunch is a comprehensive Learning Management System designed to empower educational institutions and coaching institutes. Streamline student enrollment, track academic progress, manage courses, assignments, and grades all in one intuitive platform. Foster better teacher-student collaboration and parental engagement with real-time notifications and progress reports. Elevate your educational experience with EduMunch - where teaching and learning thrive together."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  get: ^4.6.5
  pdf: ^3.10.4
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  table_calendar: ^3.0.9
  record: ^6.1.2
  audioplayers: ^5.2.1
  intl: ^0.18.1
  youtube_player_flutter: ^9.0.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bg.png
    - assets/profile.png